name: Build library jar

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install zip, unzip
      run: sudo apt update && sudo apt install zip unzip
    
    - name: Build
      run:  |
         ./build.sh
         mkdir -p /tmp/result_jar
         mv vkmod-an-libs.jar /tmp/result_jar/
      
    - name: Upload built jar
      uses: actions/upload-artifact@v4
      with:
        name: libs
        path: /tmp/result_jar/
